"""Pre-commit hook integration — install/uninstall SafeClaw git hooks."""

from __future__ import annotations

import stat
import subprocess
from pathlib import Path

from rich.console import Console

from safeclaw.policy import load_policy
from safeclaw.runner import run_plugin

HOOK_MARKER_START = "# >>> SAFECLAW_HOOK >>>"
HOOK_MARKER_END = "# <<< SAFECLAW_HOOK <<<"

HOOK_SCRIPT = """\
# >>> SAFECLAW_HOOK >>>
# Auto-generated by safeclaw init — do not edit this block manually.
python -c "
import sys
from safeclaw.hooks import run_pre_commit_hook
sys.exit(run_pre_commit_hook())
"
safeclaw_exit=$?
if [ $safeclaw_exit -ne 0 ]; then
    echo "SafeClaw pre-commit check failed. Commit aborted."
    exit 1
fi
# <<< SAFECLAW_HOOK <<<
"""


def _find_git_dir(start: Path) -> Path | None:
    """Walk up from *start* looking for a .git directory.

    Args:
        start: Directory to begin searching from.

    Returns:
        Path to the .git directory, or None if not found.
    """
    current = start.resolve()
    for parent in [current, *current.parents]:
        git_dir = parent / ".git"
        if git_dir.is_dir():
            return git_dir
    return None


def install_hook(project_root: Path, *, force: bool = False) -> Path:
    """Install the SafeClaw pre-commit hook into the git repository.

    Args:
        project_root: Root directory of the project.
        force: If True, replace existing SafeClaw hook section.

    Returns:
        Path to the hook file.

    Raises:
        FileNotFoundError: If no .git directory is found.
        RuntimeError: If SafeClaw hook already exists and force is False.
    """
    git_dir = _find_git_dir(project_root)
    if git_dir is None:
        raise FileNotFoundError("No .git directory found. Is this a git repository?")

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "pre-commit"

    existing = ""
    if hook_path.exists():
        existing = hook_path.read_text(encoding="utf-8")

    if HOOK_MARKER_START in existing:
        if not force:
            raise RuntimeError("SafeClaw hook already installed. Use --force to replace it.")
        # Remove existing SafeClaw section
        existing = _remove_safeclaw_section(existing)

    # Build the hook file content
    if not existing.strip():
        content = "#!/bin/sh\n" + HOOK_SCRIPT
    else:
        content = existing.rstrip("\n") + "\n\n" + HOOK_SCRIPT

    hook_path.write_text(content, encoding="utf-8")

    # Make executable (Unix; no-op on Windows for git bash)
    try:
        current_mode = hook_path.stat().st_mode
        hook_path.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass  # Windows may not support chmod

    return hook_path


def uninstall_hook(project_root: Path) -> bool:
    """Remove the SafeClaw section from the pre-commit hook.

    Args:
        project_root: Root directory of the project.

    Returns:
        True if the SafeClaw section was found and removed.
    """
    git_dir = _find_git_dir(project_root)
    if git_dir is None:
        return False

    hook_path = git_dir / "hooks" / "pre-commit"
    if not hook_path.exists():
        return False

    content = hook_path.read_text(encoding="utf-8")
    if HOOK_MARKER_START not in content:
        return False

    cleaned = _remove_safeclaw_section(content)

    # If only shebang/whitespace remains, delete the file
    if not cleaned.replace("#!/bin/sh", "").replace("#!/bin/bash", "").strip():
        hook_path.unlink()
    else:
        hook_path.write_text(cleaned, encoding="utf-8")

    return True


def _remove_safeclaw_section(content: str) -> str:
    """Remove the SafeClaw hook section from hook file content."""
    lines = content.splitlines(keepends=True)
    result: list[str] = []
    inside = False
    for line in lines:
        if HOOK_MARKER_START in line:
            inside = True
            continue
        if HOOK_MARKER_END in line:
            inside = False
            continue
        if not inside:
            result.append(line)
    return "".join(result)


def run_pre_commit_hook(policy_path: str = "policy.yaml") -> int:
    """Entry point called by the git pre-commit hook.

    Scans only staged files for secrets using the secrets_scan plugin.

    Returns:
        0 if clean, 1 if secrets found or error.
    """
    console = Console(stderr=True)

    # Get staged files
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=d"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        console.print(f"[red]SafeClaw: failed to get staged files: {exc}[/red]")
        return 1

    staged_files = [f for f in result.stdout.strip().splitlines() if f.strip()]
    if not staged_files:
        return 0

    # Load policy
    try:
        policy = load_policy(policy_path)
    except (FileNotFoundError, ValueError) as exc:
        console.print(f"[red]SafeClaw: failed to load policy: {exc}[/red]")
        return 1

    # Check if secrets_scan is allowed
    if "secrets_scan" not in policy.allowed_plugins:
        console.print("[yellow]SafeClaw: secrets_scan not in allowed plugins, skipping.[/yellow]")
        return 0

    # Scan each staged file
    found_secrets = False
    for filepath in staged_files:
        fpath = Path(filepath)
        if not fpath.exists():
            continue
        scan_result = run_plugin(policy, "secrets_scan", fpath)
        if scan_result.ok and "Found" in scan_result.message:
            console.print(f"[red]SafeClaw: secrets detected in staged file: {filepath}[/red]")
            console.print(scan_result.message)
            found_secrets = True

    if found_secrets:
        console.print("\n[red bold]Commit blocked — remove secrets before committing.[/red bold]")
        return 1

    console.print("[green]SafeClaw: pre-commit check passed.[/green]")
    return 0
